spring:
  profiles:
    active: "@activatedProperties@"

  application:
    name: authorization

  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"

eureka:
  instance:
    instance-id: authorization

aliyun:
  sts:
    endpoint: sts.aliyuncs.com
    read-only-role-arn: read-only
    write-only-role-arn: write-only

  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: name
    expiration-seconds: 3600

  access-key:
    id: id
    secret: secret
