apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: cangjingge
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      restartPolicy: Always
      containers:
      - name: user
        image: lgasyou/cangjingge-user:0.1.8
        env:
          - name: APP_OPTS
            valueFrom:
              configMapKeyRef:
                key: default-zone
                name: eureka-server-configmap
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: cangjingge
  labels:
    app: user-db
spec:
  ports:
    - port: 3306
  clusterIP: None
  selector:
    app: user-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
  namespace: cangjingge
spec:
  serviceName: user-db
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      restartPolicy: Always
      containers:
        - name: user-db
          image: mariadb:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: cangjingge
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: init
              subPath: init.sql
      volumes:
        - name: init
          configMap:
            name: user-db-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-db-cm
  namespace: cangjingge
data:
  init.sql: |-
    create database if not exists `cangjingge`;

    use `cangjingge`;

    create table if not exists `user`(
    `id` bigint(255) not null auto_increment,
    `username` varchar(64) not null,
    primary key (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    create table if not exists `bookshelf`(
    `id` bigint(255) not null auto_increment,
    `userId` bigint(255) not null,
    `fictionId` bigint(255) not null,
    primary key (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    create table if not exists `hibernate_sequence` (
        next_val bigint null
    );

    insert into `hibernate_sequence` (next_val) values (1);
